data_name: cinic

data_path: /home/lizhipeng/project/federated_learning/data/CINIC-10 # 224,246
partition_type: dirichlet # dirichlet、iid、n_class_non_iid     # Scheme of data division
dirichlet_alpha: 0.1  # 0.05, 0.1, 0.5, 1.0
dirichlet_threshold: 5
show_distribution: False
num_classes: 10  # class
balance: False
local_model_local_test: False
local_model_global_test: True

resumed_model: False
only_eval: False

num_worker: 3
model_name: mobilenetv2  # resnet、mobilenetv2
model_depth: ''  # lenet: 5, mobilenetv2: ''
batch_size: 50
lr_scheduler: decay  # decay cosin
lr: 0.1  # lenet: 0.01, others: 0.1
lr_decay: 0.996
lr_decay_interval: 1
momentum: 0.9
weight_decay: 0.0001
total_round: 1000
local_round: 5
save_interval: 500
save_rounds: []
optimizer: SGD

aggregation_type: fedprox_imagenet        # fedprox
num_clients: 100                # Number of total clients
sampled_ratio: 0.1              # Ratio of sampled clients in each round
mu: 0.001

