data_name: cifar

#data_path: /home/chenyaofo/datasets/cifar10 #224
data_path: /mnt/cephfs/home/lizhipeng/project/cifar10 #246, 224
#data_path: /home/dataset/cifar # 188、170, 244
partition_type: dirichlet # dirichlet、iid、n_class_non_iid     # Scheme of data division
dirichlet_alpha: 0.1  # 0.05, 0.1, 0.5, 1.0
dirichlet_threshold: 5 # 5 for dirichlet 100
show_distribution: False
num_classes: 10  # class
balance: False
local_model_local_test: False
local_model_global_test: False

resumed_model: False
only_eval: False

num_worker: 2
model_name: resnet  # vgg、resnet、mobilenetv2
model_depth: ''  # lenet: 5, mobilenetv2: ''
batch_size: 50
lr_scheduler: decay  # decay cosin
lr: 0.1  # lenet: 0.01, others: 0.1
lr_decay: 0.996
lr_decay_interval: 1
momentum: 0.9
weight_decay: 0.0001
total_round: 1000
local_round: 5
save_interval: 100
save_rounds: []
optimizer_type: SGD

aggregation_type: fedavg_imagenet        # fedavg
num_clients: 5                # Number of total clients
sampled_ratio: 1              # Ratio of sampled clients in each round

