data_name: cifar

data_path: /mnt/cephfs/home/lizhipeng/gpu022_home/project/federated_learning/data
partition_type: dirichlet # Scheme of data division
dirichlet_alpha: 0.1
dirichlet_threshold: 5
num_classes: 100  # class
balance: False

resumed_model: False
only_eval: False

num_worker: 2
model_name: resnet  # resnet、mobilenetv2
batch_size: 50
lr_scheduler: decay
lr: 0.1
lr_decay: 0.996
lr_decay_interval: 1
momentum: 0.9
weight_decay: 0.0001
total_round: 1000
local_round: 5
save_interval: 1000
save_rounds: []

aggregation_type: scaffold
num_clients: 16                # Number of total clients
sampled_ratio: 1              # Ratio of sampled clients in each round

